apiVersion: v1
kind: Pod
metadata:
  name: my-web-app
  labels:
    name: myapp
spec:
  containers:
  - name: container-apache
    image: httpd:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80



---
apiVersion: v1
kind: Service
metadata:
  name: my-single-pod-service
  labels:
    env : prod
    owner: jenya 
spec:
  selector:
    app: kgb
  ports:
  - port: 80
    name: app-listner
    protocol: TCP
    targetPort: 80
type: LoadBalancer

