#-------------------------------------------------------------
apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-replicas
  labels:
    app  : my-k8s-app
    env  : prod
    owner: jenya_topol
spec:
  replicas: 3
  selector:
    matchLabels:
      project: second-proj
  template:
    metadata:
      labels:
        project: second-proj
    spec:
      containers:
        - name : apache1-web
          image: httpd:latest
          ports:
            - containerPort: 80
