#-------------------------------------------------------------
apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app : my-k8s-app
spec:
  selector:
    matchLabels:
      project: first proj
  template:
    metadata:
      labels:
        project: firat-proj
    spec:
      containers:
        - name : apache-web
          image: httpd:latetst
          ports:
            - containerPort: 80
