
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app-deployment
spec:
  selector:
    matchLabels: 
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: kgb
    spec:
      containers:
      - name: kgb-web(apache)
        image: httpd:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
