apiVersion: v1
kind: Pod
metadata:
  name: my-web-app
  labels:
    name: myapp
spec:
  containers:
  - name: container-apache
    image: httpd:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
